name: 'Java Test GitHub Actions'

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: ' 5 * * * * '

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies
        run: npm install
      - name: Build with Maven
        run: mvn compile && mvn exec:java -Dexec.mainClass="cn.xiuminglee.action.Ming"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

